---
title: "FlightsDataHmwk3"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(nycflights13)
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
```

```{r}
#Problem 1
#Make a table that describes each plane. It should have a column for tailnum, another column for average arrival delay, and another for the year the plane was manufactured.
head(flights)
head(planes)
prob1 = flights %>% 
  group_by(tailnum) %>% 
  summarize(mean_arr_delay = mean(arr_delay, na.rm=T)) %>% 
  left_join(planes) %>% select(tailnum:year)
head(prob1)
```

```{r}
#Problem 2
#Make a table where each row is a day of the year. The first column is the date. The 2:4 columns give the number of (scheduled) departures from EWR, LGA, and JFK.

prob2 = flights %>%
  mutate(day_year = date(time_hour))%>%
  mutate(day_number = yday(time_hour))%>%
  group_by(day_year, origin) %>%
  summarise(deps= sum(!is.na(sched_dep_time))) %>%
  pivot_wider(names_from = origin, values_from = deps)
head(prob2)

ggplot(prob2, aes(x = yday(day_year))) +
  geom_point(aes(y=EWR,color = "EWR")) +
  geom_point(aes(y=JFK, color ="JFK")) +
  geom_point(aes(y=LGA, color = "LGA"))
```

```{r}
#Problem 3
#Make a table where each row is a day of the year. Each destination airport is a column. The elements (day x destination) give the number of flights to that destination. What should NA’s be?
#NAs should be 0.
prob3 = flights %>% 
  mutate(day_year=date(time_hour)) %>% 
  group_by(day_year,dest) %>% 
  summarise(num_arrive = sum(!is.na(arr_time))) %>%
  pivot_wider(names_from = dest, values_from = num_arrive, values_fill = list(num_arrive = 0))
head(prob3)
```
